### PR TITLE
Blips changes

### PR DESCRIPTION
**Pull request by Urek00Bg**
Faster and easier way to rename the blips

### CODE REVIEW

**Comment by Tuncion** [comment]
Hello @Urek00Bg could you elaborate on why your implementation is better? 
Because we currently have the possibility to customize the blip individually for each prop, with you, we would now have a generalization.

So your goal is to create a standard for XY name?

**Comment by Urek00Bg** [comment]
My idea was to add the blip names to the locale files, that way it would be more user friendly for the users and easier since 99% of the setup would be in 1 file at 1 specific place

**Comment by Urek00Bg** [comment]
Failed to do so as explained in the ticket and had no time to try again since I had to travel right after

**Review by Tuncion — CHANGES_REQUESTED** [review]
Need to change:

- Use PascalCase for Variables e.g. ChristmasPresentBlip
- Please initialize the variables directly after the comment `-- Dream Christmas Settings` in line 10

**Comment by Urek00Bg** [comment]
Updated

**Pull request merged**
